[project]
name = "repl-nix-weirdmoralrpg"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "nltk",
    "numpy",
    "ollama==0.4.3",
    "pandas",
    "requests>=2.32.3",
    "scikit-learn",
    "scipy",
]
